In [3]:
import numpy as np
import pandas as pd


In [18]:
import math

In [4]:
"""Esercizio 1
Abbiamo una lista di liste: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] 
Che tipo di struttura dati o matematica potrebbe rappresentare? 
Notare che tutte le liste "interne" sono della stessa dimensione 
Come facciamo per accedere ad un elemento in particolare?"""

mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [5]:
mat_array = np.array(mat)

In [6]:
mat_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
mat_array.shape #otteniamo quante liste, con quanti elementi

(3, 5)

In [13]:
mat_array[0,:] #il primo numero rappresente la prima quadra è lo 0,
               #la seconda 1, la terza 2. il secondo numero rappresenta l'elemento che vogliamo prendere

array([0, 1, 2, 3, 4])

In [20]:
"""Esercizio 2
Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() 
e la variabile .pi la riconoscete?"""


print("SIN di 90",math.sin(90),"COSEN di 90",math.cos(90))

SIN di 90 0.8939966636005579 COSEN di 90 -0.4480736161291701


In [21]:
print("SIN di 90",math.sin(math.pi/2),"COSEN di 90",math.cos(math.pi/2))

SIN di 90 1.0 COSEN di 90 6.123233995736766e-17


In [23]:
math.factorial(24)

620448401733239439360000

In [24]:
"""Esercizio 3
Proviamo a eseguire math.degrees(math.pi) 
Qual è e cosa significa il risultato? 
Per saperne di più su questa funzione possiamo usare help(math.degrees)"""

print(math.degrees(math.pi))

#La funzione math.degrees() converte un angolo da radianti a gradi. Poiché math.pi rappresenta il valore di π in radianti, 
#math.degrees(math.pi) restituirà l'equivalente di 180 gradi, 
#poiché un semicerchio (π radianti) corrisponde a 180 gradi in un cerchio completo.

180.0


In [25]:
"""Esercizio 4 
L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: 
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 
trasformiamola in un array NumPy (casting): lst = np.array(lst) e rispondiamo alle domande del CEO della Object SpA: 
• qual è stata la vendita massima mensile? E quella minima? 
• quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono? 
• quali sono le vendite minori di 3000 oggetti?
• in media quanti oggetti sono stati venduti?"""

lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 

In [26]:
lst = np.array(lst)

In [41]:
#qual è stata la vendita massima mensile? E quella minima?
print("Max",lst.max())
print("Min",lst.min())

#quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono?
filter1 = lst[lst > 4999]
print("Maggiori di 4999", filter1)
print("le vendite mensili maggiori di 4999 oggetti",len(filter1))

#quali sono le vendite minori di 3000 oggetti?
filter2 = lst[lst < 3000]
print("Minori di 3000", filter2)

#in media quanti oggetti sono stati venduti?
print("Media al mese",round(lst.mean(), 2)) #con round e ",2" vuol dire che ho arrotondato a 2 cifre dopo la virgola

Max 8150
Min 1280
Maggiori di 4999 [5500 7200 6410 8150 7100 5350]
le vendite mensili maggiori di 4999 oggetti 6
Minori di 3000 [2000 1280 1900 2500]
Media al mese 4634.17


In [45]:
"""Esercizio 5
Consideriamo il seguente dizionario: 
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000} 
Consideriamo ora la seguente Series: 
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
index=range(1997, 2005))
Possiamo accedere alle stesse informazioni nello stesso modo: fatturati_dict[1997] fatturati_series[1997]
Dunque qual è la differenza tra i due tipi di dato? 
Cosa potremmo fare con la Series che non possiamo fare con il dizionario?"""

#Dizionario
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}

#Serie Pandas
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
index=range(1997, 2005))

print("Tipo di valore del dizionario", type(fatturati_dict[1997]))
print("Tipo di valore della serie", type(fatturati_series[1997]))

#Cosa potremmo fare con la Series che non possiamo fare con il dizionario?
print("Massimo della serie", max(fatturati_series))


Tipo di valore del dizionario <class 'int'>
Tipo di valore della serie <class 'numpy.int64'>
Massimo della serie 25000


In [53]:
"""Esercizio 6
L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, 
memorizzato in un ndarray: 
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] ) 
L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi:
• con un ciclo for 
• con il masking"""

stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] ) 
print(stipendi)

#ciclo for
lista_stipendi = []
lista_stipendi_raddoppiati = []

for stipendio in stipendi:
    lista_stipendi_raddoppiati.append(stipendio*2)

#LIST COMPREHENSION
#lista_stipendi_raddoppiati2= [x*2 for x in stipendi]        possiamo scrivere x o anche stipendio, poichè rappresenta il singolo elemento
#print(lista_stipendi_raddoppiati2)

print("Lista stipendi raddoppiati CICLO FOR:", lista_stipendi_raddoppiati)


#masking
lista_stipendi_raddoppiati_numpy = stipendi*2
print("Lista stipendi raddoppiati MASKING:", lista_stipendi_raddoppiati_numpy)

[ 100  200  300  400  500  600  700  800  900 1000]
Lista stipendi raddoppiati CICLO FOR: [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]
Lista stipendi raddoppiati MASKING: [ 200  400  600  800 1000 1200 1400 1600 1800 2000]
